# This is a GitHub Actions workflow file.
# It defines a set of automated jobs that will run in response to events,
# such as pushing code to the repository.

# Name of the workflow, which will be displayed on the "Actions" tab in GitHub.
name: Python ETL CI/CD Pipeline

# Controls when the workflow will run.
# We're configuring it to run on every push to the 'main' branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on. We're using the latest Ubuntu version.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up a specific version of Python.
      # This ensures our code runs in a consistent environment.
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install our project's dependencies from requirements.txt.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4: Run the data pipeline.
      - name: Run ETL Data Pipeline
        run: python3 data_pipeline.py

      # Step 5: (Placeholder for future tests)
      - name: Run API tests (Placeholder)
        run: echo "No API tests configured yet, but this is where they would go."

      # Step 6: Deploy to Hugging Face Spaces
      # This action pushes the repository to a Hugging Face Space.
      # It will only run on pushes to the 'main' branch, not on pull requests.
      - name: Deploy to Hugging Face Spaces
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        # UPDATED to a newer version of the action
        uses: huggingface/hub-action@v0.14
        with:
          # You need to create this secret in your GitHub repository settings.
          hf_token: ${{ secrets.HF_TOKEN }}
          # IMPORTANT: Replace this with the ID of your Hugging Face Space.
          repo_id: "TurnerR0und/etl-dashboard"
          repo_type: space
          commit_message: "Deploying from GitHub action"

