# .github/workflows/main.yml

name: Build, Test, and Deploy ETL Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with Pytest
        run: |
          pytest

      - name: Run ETL Data Pipeline (Integration Check)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python3 data_pipeline.py

  deploy:
    # This job only runs if the 'build-and-test' job completes successfully
    needs: build-and-test
    # This job only runs on pushes to the main branch, not on pull requests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Use a direct git push for deployment
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add space https://TurnerR0und:${HF_TOKEN}@huggingface.co/spaces/TurnerR0und/etl-dashboard
          git push --force space main

