# This is a GitHub Actions workflow file.
# It defines a set of automated jobs that will run in response to events,
# such as pushing code to the repository.

# Name of the workflow, which will be displayed on the "Actions" tab in GitHub.
name: Python ETL CI/CD Pipeline

# Controls when the workflow will run.
# We're configuring it to run on every push to the 'main' branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on. We're using the latest Ubuntu version.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      # We fetch the full history, which is required for pushing to a different remote.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up a specific version of Python.
      # This ensures our code runs in a consistent environment.
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install our project's dependencies from requirements.txt.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4: Run the data pipeline.
      - name: Run ETL Data Pipeline
        run: python3 data_pipeline.py

      # Step 5: (Placeholder for future tests)
      - name: Run API tests (Placeholder)
        run: echo "No API tests configured yet, but this is where they would go."

      # Step 6: Deploy to Hugging Face Spaces using a direct Git push.
      # This step will only run on pushes to the 'main' branch.
      - name: Deploy to Hugging Face Spaces
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          # Your HF Token is used for authentication.
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Add the Hugging Face Space as a new Git remote.
          # The URL is constructed using your HF username and the token for authentication.
          git remote add hf https://user:${HF_TOKEN}@huggingface.co/spaces/TurneR0und/etl-dashboard
          
          # Force push the 'main' branch from your GitHub repo to the 'main' branch of the Hugging Face Space remote.
          # The --force flag is used to ensure the Space is an exact mirror of your GitHub repo.
          git push --force hf main

